### PR TITLE
Improve Japanese Locale

### PR DESCRIPTION
**Pull request by tokkiyaa**
- fixed Japanese locale(from ja-JA to ja-JP)
- Use "ja-JP" locale when user's browser language is Japanese
- Updated translation

@cheemurakami could you take a look and comment?

### CODE REVIEW

**Comment by cheemurakami** [comment]
Looks great, thanks for correcting my kanji mistake! 👍

**Review by Kedyn — APPROVED** [review]

**Comment by Kedyn** [comment]
@tokkiyaa first of all, thank you  for your contribution. Would tou mind adding yourself to the readme, thank you in advance.

**Comment by tokkiyaa** [comment]
@Kedyn 
thanks. added my name.

**Review by Kedyn — APPROVED** [review]

**Comment by Kedyn** [comment]
Awesome thank you

**Pull request merged**
