### PR TITLE
Czech translation

### LINKED ISSUE #105: Czech Translation For The Page
I didn't know to make an issue or pull request so I made this basically I wanted to make Czech translations for the page because it's actually my first language and I wanted it because my friends who don't know too much about English wanted to use this but couldn't because they don't know that much English only the basic sentences if anyone knows how to help to get the translation on the page please comment thank you.

### PR DESCRIPTION
**Pull request by Drison64**
Closes #105 

Hello, **this may not be the final version**. I will ask my friends if they would change anything.

### CODE REVIEW

**Comment by Kedyn** [comment]
Hi, I am still working on some things that might change a few other things that will need translation, therefore I will wait for merging this contribution. Thank you for understanding, I will be letting you know once there are no new changes to the translation file for this next release.

**Comment by Drison64** [comment]
Hi, sure, take your time. 🙂

**Comment by Kedyn** [comment]
Hi, we've made all the new changes for the new version, if you would like to update you can do it now. Thank you.

**Comment by Drison64** [comment]
> Hi, we've made all the new changes for the new version, if you would like to update you can do it now. Thank you.

Hello, I updated the translation and I think it is done. You can merge it.

**Review by Kedyn — APPROVED** [review]

**Pull request merged**
