### PR TITLE
Created Dutch Translation

### PR DESCRIPTION
**Pull request by pboschma**
Took some time to appreciate this tool and decided to create a dutch translation!

I purposely left some words or letters english, since the Dutch people will understand this a bit better in some cases (While playing this game)

### CODE REVIEW

**Comment by pboschma** [comment]
I just noticed a mistake in my code. "Hitliste" is incorrect". I'll create a new PR.

**Comment by francistse23** [comment]
hey pboschma, thank you for your contribution!

just a heads up, we are pausing translation PRs right now as we are expecting some UI changes that may require revised/new translations. we'll leave translations related PRs open for now

we'll ping you once we have finalized the changes

also, feel free to add yourself to the `Author and acknowledgements` section in the readme

**Comment by Kedyn** [comment]
I think that is all the new things we will adding for the next version, if you still willing to do the translation please do so.

**Comment by pboschma** [comment]
Well.

Maybe I'm blind, but when I open the new English Language File I don't see any missing or new translations. This should still work fine.

**Pull request closed without merging**
