### PR TITLE
Save

### LINKED ISSUE #91: State Not Preserved on Refresh
From feedback:
> Should add option for cookies to save your information so you don't lose it every time you refresh

I did a quick test and noticed only notes are saved, but not players, scores, etc. 

If this was intended in any way, please close the issue

### PR DESCRIPTION
**Pull request by Kedyn**
Fixes #91 

- Saves players and scores to localstorage

I will be adding maps (issue #100) to redux, so the state remains the same when switching between tabs, should we also save this data to storage?

### CODE REVIEW

**Comment by francistse23** [comment]
i'm not sure if it's worth the effort... i think we talked about potentially removing maps in the mobile version right? because of how hard it is to move the characters around with a small screen

**Comment by Kedyn** [comment]
That is also a solution for the maps problem.

**Comment by francistse23** [comment]
also, the changes in this PR seem to overlap with some/most of the changes in your other PR for #101.

might be easier to review once we merged the other PR in and hopefully the files changed will update?

**Comment by Kedyn** [comment]
Yes, just noticed that.

**Comment by Kedyn** [comment]
Ok, note to self: make sure you branch from master every time or files won't be updated.

**Comment by francistse23** [comment]
did you do a `git pull` ? that might update the files changes since it compares it with the `master` branch

**Comment by Kedyn** [comment]
Yeah it will not update it here

**Comment by francistse23** [comment]
i see. that's fine, i'll just review the 2 commits that have to do with the save state

**Review by francistse23 — APPROVED** [review]
I trust that you have tested this. looks good

someone commented yesterday:
> I'd like a button to reset the players on the left, while keeping their names.

not sure what he/she means... because we already that the `Reset Round` button

**Comment by Kedyn** [comment]
Yeah they might of just missed it, same with the one that does not about the settings to change language.

**Pull request merged**
