### PR TITLE
Enable editing/read-only modes for player colours and names

### PR DESCRIPTION
**Pull request by leeeennyy**
Added feature to enable editing/read-only modes for player colours and names as per #19 

I opted to use a button with text to toggle between the modes, but don't know what they're meant to be in the other languages - I didn't want to use Google Translate in case it was severely incorrect.

### CODE REVIEW

**Comment by chilblane** [comment]
Going to check this out locally and review the UI changes

**Comment by chilblane** [comment]
@leeeennyy for the button placement, instead of absolute positioning, the way I would approach it is to make the reset players and lock palyers button siblings, and put them in a container similar to the buttons in the controls panel (settings / about /changelog). this way they nicely sit next to each other, 1rem from the last PlayerSection, and the reset player button disappears on desktop as it has before.

**Comment by leeeennyy** [comment]
Mobile: image
Desktop: 
image

**Comment by chilblane** [comment]
perfecto 👌

**Comment by leeeennyy** [comment]
@chilblane Sweet as. I've rebased with master so merge should be okay now. 

Do you know how we get the translations for other languages as well? The other languages still have lock/unlock in english.

**Comment by chilblane** [comment]
We know that we need to review what we have to fix for translations; my UI update added/changed a few as well. I will let the maintainers figure out how they want to organize that and pass this PR off to them @Kedyn @francistse23

**Review by Kedyn — APPROVED** [review]

**Pull request merged**
